### ISSUE TITLE
Feature Request | restrict ammount of shown calendar items

### ISSUE THREAD

**Issue by androiduser5** [theawless/EventLock#10]
Dear Devs of EventLock,
it would be a nice feature if there would be a possibility to restrict the ammount of shown calendar events. For example, that there are obly four events displayed and not all of the whole day. It would be a good feature to get the right mix of easyness and privacy. 
Greetings
Sebastian

**Comment by theawless** [comment]
You can try "Days till" in the settings. Does that not solve your purpose?
I know it's not a complete limit but if you limit it to say 1 or 2 then lesser number of events will be shown.
