### ISSUE TITLE
Possible to show multiple events vertical at same time?

### ISSUE THREAD

**Issue by fallenwout** [theawless/EventLock#11]
This is really coming along nicely!
Is it possible to use more vertical space to display a couple of events at the same time?

**Comment by theawless** [comment]
Yes I think I'll do that for the next update.

**Comment by theawless** [comment]
Btw I see that you've been using my application for long, it's intended to do these:
* Update all events after midnight.
* Update the current event(the one in bold) after it ends.
* Scroll back to the current event when screen is turned off and on once.

Essentially it should show the running event, if there are more than two running events then it should show the one which started later.
If there are no running events then it should show the upcoming event.
If none of above is there, it should show the last "no more events".

Can you tell me whether all that happens?

**Comment by theawless** [comment]
![screenshot_20161216-174947](https://cloud.githubusercontent.com/assets/15650532/21262618/600ccd0c-c3b8-11e6-98da-eb2288cdc16b.png)

This is what i was thinking. The events number on page can be chosen (for my case 3).
You can scroll left/right to see others.

**Comment by fallenwout** [comment]
That's it!

**Comment by theawless** [comment]
That takes up a lot of space though

**Comment by fallenwout** [comment]
Yes it takes a lot of space. You already let users select the range, maybe you can combine it with an option to select how many lines/events to show simultaniously.
So if you select 3days, 2 lines/events. It will be a scrollable list of pairs, no matter how low the list..
If you have good eyes, you can change to font smaller and let users pick 3days and 3lines/events.
I know you are limited by the notification area.

And if you really want to go crazy, you can apply that logic to rows. For example 2 events in 1 row instead of 2 events in 1 column(=2 rows).

Example 3 events in 1 row:
Divide screen in 3 columns (1 row). Make it a fix size in relation to the set margings. If you fix the size, you can align them to the left of their column which will be more consistent than making the width variable to the event. If the event title is to long, let it fade out at the start of a new column.
![600ccd0c-c3b8-11e6-98da-eb2288cdc16b](https://cloud.githubusercontent.com/assets/24213163/21265656/be776c82-c3a2-11e6-8e95-cbaf1e1ced61.png)

**Comment by theawless** [comment]
Right I'll make options for everything! Then I'll give a few presets. Thanks for your input.
