### ISSUE TITLE
Last horizontal scroll shows the free text for no events

### ISSUE THREAD

**Issue by fallenwout** [theawless/EventLock#12]
If you have events and scroll horizontally all the way to the left, the text you type at "free text when no events" is shown.

**Comment by theawless** [comment]
Oh that's a feature actually. If you read carefully it says"no more events". It will be shown after all events in the days till range have been completed.

**Comment by theawless** [comment]
You can clear it if you don't want anything to be shown.

**Comment by fallenwout** [comment]
Oh I thought it was for when there are no events in de preset days. Because i had it at "lot's of free time".
You should only display it when event-count is 0.

**Comment by theawless** [comment]
But then how should I show that there are no more events left in range?

**Comment by fallenwout** [comment]
I'm don't know about android programming. So i might suggest unrealistic things.

You can add the android "glow" end of list.

**Comment by theawless** [comment]
It's not about the end. I'm saying current event which is in bold -- always shows the upcoming/ongoing event. But if all events are over in the range? What should I show then?

**Comment by fallenwout** [comment]
When there are no events in the current range it should show the "free text". So for example if you set your range to 3 days and there is only an event on day 5, show the free text. Letting people adjust that is a really good idea. User can set it manually to "nothing to do for 3 days" (according to the preset range) or "lazy bastard" or "time for hobbies".
Otherwise just show the horizontal/vertical list of events for 3 days and highlight current day event?

**Comment by theawless** [comment]
Eventlock shows events from start of today  to the end of days till (3 days). So if all events for today are over and there are no events for 3 days. Then what should be shown?

**Comment by fallenwout** [comment]
I will quote myself :)

> When there are no events in the current range it should show the "free text". 

When there are events, just show them without the "free text"

**Comment by theawless** [comment]
Options for this too, I like to see the text in my list.
