### ISSUE TITLE
Hide the day's past events

### ISSUE THREAD

**Issue by humanplayer2** [theawless/EventLock#19]
Thank you for this! It is an absolutely wonderful add-on which I am sorry to not have discovered long ago!

My question: Would it be possible to hide the day's past events to the effect that an event running from 9 to 10 does not still show at 11?

This would severely de-clutter the view of event-heavy days, letting one at a glance see what's up next.

Kinf regards, 
Rasmus

**Comment by theawless** [comment]
The past events for the day are not removed from the list. But the current event (the one which has a bold title) is always visible at the first glance i.e. you don't have to scroll forward to find it. 

<img src="https://user-images.githubusercontent.com/15650532/34896701-d2721234-f810-11e7-8e17-4197882d4d72.png" width="256" height="455" />

For example in my screen, Writing Systems lecture is over so it is not highlighted, and the next one is automatically highlighted.

**Comment by humanplayer2** [comment]
Yeah, I see what you mean, and it's a nice design choice. Personally, I'would just prefer to be rid of the clutter of past events: If you like such, consider it a feature request.
In any case, the module is hugely beneficial, so thank you for it!
