### ISSUE TITLE
Moving the items down

### ISSUE THREAD

**Issue by Mrtenz** [theawless/EventLock#20]
It would be nice if it was configurable to move the items down a little bit. At least on the ROM I'm using (Resurrection Remix, Android 8.1), they are very close to the date, as you can see on [this screenshot](https://i.imgur.com/xU3P4hf.png). I know there is a padding option, but margin would look nicer.

**Comment by theawless** [comment]
Hey, I'll consider adding margins in the newer version. Perhaps margins would be a better option than padding altogether.

**Comment by theawless** [comment]
I tried the margins too, but they give the exact same results. 

PS: I hope you are looking at gismo padding and not title/time paddings.
