### ISSUE TITLE
All Day Calendar events not showing

### ISSUE THREAD

**Issue by connorwaldo** [theawless/EventLock#23]
I have some all day calendar events that are sent to All Day within the Google Calendar settings for that particular event that do not show with event lock. When I move these particular events to a specific time within the day then it will show in eventlock. Can you add the functionality for all day calendar events to show as well? Thanks!

**Comment by theawless** [comment]
My all day events work just fine. Are your events multiple days long?

**Comment by theawless** [comment]
Fixed in 266f8191e5c2bdf3aa44a277b22e32987b64850e

**Comment by connorwaldo** [comment]
Is there an easy way to update it?

Sincerely,
Connor W.

-- 
Connor Waldo
waldoctg@gmail.com

**Comment by theawless** [comment]
You can find the updated version in xposed store

**Comment by connorwaldo** [comment]
Keeps saying event lock has stopped.

**Comment by theawless** [comment]
Clear the app data, doesn't it show you a warning?

**Comment by connorwaldo** [comment]
Worked. Thanks!
