### ISSUE TITLE
New logo / icon

### ISSUE THREAD

**Issue by mansya** [theawless/EventLock#24]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by theawless** [comment]
Hey! I appreciate your help. I'm not sure when I'll release the next version as I released one recently, and I have no more important bug fixes or feature requests (yet).

**Comment by mansya** [comment]
I designed this app for quick release and interesting when in use. :-D
I have designed it. What do you think ? do you like it ?
![eventlock](https://user-images.githubusercontent.com/33461607/41736400-882f9c04-75b6-11e8-9909-716e3ec92e32.png)

**Comment by theawless** [comment]
Thanks, I like it very much! We can use this in the new release. Can you create a pull request?

**Comment by mansya** [comment]
I have upload all files to this link.
https://drive.google.com/open?id=1EOlV81Hfh_VUqCorA10xMNHoz9vMTsXe

And I have sent you Pull Requests. please check

**Comment by theawless** [comment]
@mansya I added your logos in ac5d185601eabe69019a673e6a9c80514f8eba1a. Thanks for your help!
