### ISSUE TITLE
wrong timezone displayed

### ISSUE THREAD

**Issue by chuntera** [theawless/EventLock#25]
I installed 3.3 via Xposed framework on my Android 8.1 phone.

The events displayed on lockscreen use timezone event was created in not current timezone of the phone.

For example I create a 9am calendar event in Los Angeles (Pacific TZ). Then I travel to New York (Eastern TZ). The event should be 12pm New York time but eventlock still shows event as 9am.

**Comment by theawless** [comment]
Did you try pressing the refresh button in EventLock?

**Comment by theawless** [comment]
Evenlock should automatically update the events when the timezone is changed.

**Comment by chuntera** [comment]
I tried refresh, no difference. This issue looks to be specific to calender I import from my exchange account.

**Comment by theawless** [comment]
Does calendar show it correctly?

**Comment by chuntera** [comment]
Yes shows correctly in calendar app.

**Comment by jagjordi** [comment]
Was this issue finally resolved? I am having the same problem. Google Calendar displays the correct time but eventlock dos not.
Thanks

**Comment by theawless** [comment]
@jagjordi does thing happen to you only for exchange accounts too?

**Comment by jagjordi** [comment]
I dont really know. Its the calendar that I export from my university schedule. I add it at google calendar. The google calendar displays it correctly.
I can send you the calendar link if you want
Thanks

**Comment by theawless** [comment]
I don't possess a phone anymore on which I can develop this application. I've found the error and I can try to fix it. Can you help me test it if I provide you the apk?

**Comment by jagjordi** [comment]
Sure!

**Comment by theawless** [comment]
@jagjordi can you test this (i've put it as a zip because github blocks apk uploads)?
[app-release.zip](https://github.com/theawless/EventLock/files/2342453/app-release.zip)

**Comment by jagjordi** [comment]
Apparently it works perfect now. Thank you very much!

**Comment by theawless** [comment]
Fixed in affe67a
