### ISSUE TITLE
crash on open

### ISSUE THREAD

**Issue by ibrokemypie** [theawless/EventLock#3]
`10-17 13:23:37.966 W/System  (24454): ClassLoader referenced unknown path: /data/app/com.gobbledygook.theawless.eventlock-2/lib/arm64`

**Comment by theawless** [comment]
Did this start after a new update?
Can you try cleaning the app data? (Settings -> Applications -> EventLock -> Storage -> Clear data)

Can you post more of the log file? That is just a warning, 
W/System - warning
E/... - error
The error would have something like this "FATAL EXCEPTION..."

**Comment by ibrokemypie** [comment]
yes this was after updating, and it seems clearing the data has fixed it, thanks!
