### ISSUE TITLE
Google now reminders

### ISSUE THREAD

**Issue by Dineshachari** [theawless/EventLock#5]
Please add reminders set in Google now to show in the lock screen.

**Comment by theawless** [comment]
But don't we already get notifications for reminders? What's the use for it?

**Comment by d1358531** [comment]
I have a event, from Google calendar, in 3 days and it's not showing up.

**Comment by theawless** [comment]
@d1358531 did you try increasing the end time in settings? You need to make it 4 days.
Also if you added the event recently, then you might need to run the main app once to refresh event list.

**Comment by d1358531** [comment]
I made the end time 10 days, plus Halloween is today, but it said it was yesterday.  Should I uninstall then reinstall the app?

**Comment by theawless** [comment]
@d1358531 I think this is a bug then. I think the application is using the UTC (universal coordinated time) and not your local time. As far I know this only happens with All-day events.

Try this settings > date & time > (re-) enable automatic time-zone
Run calendar once
Run eventlock

If this does not work then hopefully I will be able to fix the issue in the next update. Sorry for the inconvenience.

**Comment by d1358531** [comment]
I didn't do anything different, but the event finally showed up...thanks for your help!
