### ISSUE TITLE
Calendar events not showing

### ISSUE THREAD

**Issue by Latschenharry** [theawless/EventLock#8]
After updating i can´t see any of my events anymore.
I already tried your tips and even fully reinstalled the app.

Phone: OnePlus 2
OS: OxygenOs 3.1.0
Android: 6.0.1

**Comment by theawless** [comment]
Did you select the calendars and input days till correctly?
Also does the preview shows any events?
What is your time zone? Is it set to automatic?

**Comment by Latschenharry** [comment]
i ticked all my calendars and the input days till is on 3 days. on clicking preview it crashes.
time zone is also set to automatic.

**Comment by theawless** [comment]
Does it also crash on pressing refresh?

**Comment by Latschenharry** [comment]
yes it does

**Comment by theawless** [comment]
It would be helpful if you could give me your xposed log.

**Comment by Latschenharry** [comment]
12-13 20:12:31.114 I/Xposed  (  576): -----------------
12-13 20:12:31.114 I/Xposed  (  576): Starting Xposed version 86, compiled for SDK 23
12-13 20:12:31.114 I/Xposed  (  576): Device: ONE A2003 (OnePlus), Android version 6.0.1 (SDK 23)
12-13 20:12:31.114 I/Xposed  (  576): ROM: ONE A2003_24_160826
12-13 20:12:31.114 I/Xposed  (  576): Build fingerprint: OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447840920:user/release-keys
12-13 20:12:31.114 I/Xposed  (  576): Platform: arm64-v8a, 64-bit binary, system server: yes
12-13 20:12:31.114 I/Xposed  (  576): SELinux enabled: yes, enforcing: yes
12-13 20:12:31.147 I/Xposed  (  576): -----------------
12-13 20:12:31.147 I/Xposed  (  576): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-13 20:12:31.541 I/Xposed  (  576): Detected ART runtime
12-13 20:12:31.557 I/Xposed  (  576): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-13 20:12:31.865 I/Xposed  (  576): Loading modules from /data/app/io.mh0rst.twitchnoads-2/base.apk
12-13 20:12:32.019 I/Xposed  (  576):   Loading class io.mh0rst.twitchnoads.BlockAds
12-13 20:12:32.020 I/Xposed  (  576): Loading modules from /data/app/io.kuenzler.android.stayawake-1/base.apk
12-13 20:12:32.068 I/Xposed  (  576):   Loading class io.kuenzler.android.stayawake.Xposed
12-13 20:12:32.089 I/Xposed  (  576): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
12-13 20:12:32.117 I/Xposed  (  576):   Loading class de.defim.apk.bootmanager.Xposed
12-13 20:12:32.121 I/Xposed  (  576):     [BootManager] initialized
12-13 20:12:32.121 I/Xposed  (  576):   Loading class de.defim.apk.bootmanager.Xcheck
12-13 20:12:32.122 I/Xposed  (  576): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-2/base.apk
12-13 20:12:32.137 I/Xposed  (  576):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
12-13 20:12:32.138 I/Xposed  (  576): Loading modules from /data/app/com.devadvance.rootcloak2-1/base.apk
12-13 20:12:32.157 I/Xposed  (  576):   Loading class com.devadvance.rootcloak2.RootCloak
12-13 20:12:32.157 I/Xposed  (  576): Loading modules from /data/app/io.gavinhungry.xposed.oneplus.noquickpulldown-1/base.apk
12-13 20:12:32.171 I/Xposed  (  576):   Loading class io.gavinhungry.xposed.oneplus.noquickpulldown.NoQuickPulldown
12-13 20:12:32.172 I/Xposed  (  576): Loading modules from /data/app/com.ceco.sbdp-1/base.apk
12-13 20:12:32.189 I/Xposed  (  576):   Loading class com.ceco.sbdp.ModSbdp
12-13 20:12:32.191 I/Xposed  (  576): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
12-13 20:12:32.227 I/Xposed  (  576):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
12-13 20:12:32.240 I/Xposed  (  576): Loading modules from /data/app/com.glauber.android.xposed.volumesliderdelayfix-1/base.apk
12-13 20:12:32.257 I/Xposed  (  576):   Loading class com.glauber.android.xposed.volumesliderdelayfix.App
12-13 20:12:32.263 I/Xposed  (  576): Loading modules from /data/app/com.jodelXposed-1/base.apk
12-13 20:12:32.328 I/Xposed  (  576):   Loading class com.jodelXposed.App
12-13 20:12:32.353 I/Xposed  (  576): Loading modules from /data/app/com.jt5.xposed.chromepie-1/base.apk
12-13 20:12:32.387 I/Xposed  (  576):   Loading class com.jt5.xposed.chromepie.ChromePie
12-13 20:12:32.389 I/Xposed  (  576): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
12-13 20:12:32.425 I/Xposed  (  576):   Loading class ma.wanam.youtubeadaway.Xposed
12-13 20:12:32.426 I/Xposed  (  576): Loading modules from /data/app/tw.fatminmin.xposed.networkspeedindicator-1/base.apk
12-13 20:12:32.453 I/Xposed  (  576):   Loading class tw.fatminmin.xposed.networkspeedindicator.Module
12-13 20:12:32.456 I/Xposed  (  576): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
12-13 20:12:32.507 I/Xposed  (  576):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
12-13 20:12:32.526 I/Xposed  (  576): [Android N-ify] [INFO] XposedHook: Version 0.2.0 (5)
12-13 20:12:32.526 I/Xposed  (  576): [Android N-ify] [INFO] XposedHook: Official Build; Release: true (release)
12-13 20:12:32.527 I/Xposed  (  576): [Android N-ify] [WARNING] XposedHook: Can't read prefs file, default values will be applied in hooks!
12-13 20:12:32.527 I/Xposed  (  576): Loading modules from /data/app/com.gobbledygook.theawless.eventlock-1/base.apk
12-13 20:12:32.631 I/Xposed  (  576):   Loading class com.gobbledygook.theawless.eventlock.hooks.XposedUtilsHook
12-13 20:12:32.642 I/Xposed  (  576):   Loading class com.gobbledygook.theawless.eventlock.hooks.LockscreenHook
12-13 20:12:32.659 I/Xposed  (  576): Loading modules from /data/app/com.czbix.xposed.wifipassword-2/base.apk
12-13 20:12:32.678 I/Xposed  (  576):   Loading class com.czbix.xposed.wifipassword.Patch
12-13 20:12:41.244 I/Xposed  (  577): -----------------
12-13 20:12:41.244 I/Xposed  (  577): Starting Xposed version 86, compiled for SDK 23
12-13 20:12:41.244 I/Xposed  (  577): Device: ONE A2003 (OnePlus), Android version 6.0.1 (SDK 23)
12-13 20:12:41.244 I/Xposed  (  577): ROM: ONE A2003_24_160826
12-13 20:12:41.244 I/Xposed  (  577): Build fingerprint: OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447840920:user/release-keys
12-13 20:12:41.244 I/Xposed  (  577): Platform: arm64-v8a, 32-bit binary, system server: no
12-13 20:12:41.244 I/Xposed  (  577): SELinux enabled: yes, enforcing: yes
12-13 20:12:41.246 I/Xposed  (  577): -----------------
12-13 20:12:41.246 I/Xposed  (  577): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-13 20:12:41.567 I/Xposed  (  577): Detected ART runtime
12-13 20:12:41.582 I/Xposed  (  577): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-13 20:12:41.769 I/Xposed  (  577): Loading modules from /data/app/io.mh0rst.twitchnoads-2/base.apk
12-13 20:12:41.855 I/Xposed  (  577):   Loading class io.mh0rst.twitchnoads.BlockAds
12-13 20:12:41.856 I/Xposed  (  577): Loading modules from /data/app/io.kuenzler.android.stayawake-1/base.apk
12-13 20:12:41.898 I/Xposed  (  577):   Loading class io.kuenzler.android.stayawake.Xposed
12-13 20:12:41.914 I/Xposed  (  577): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
12-13 20:12:41.934 I/Xposed  (  577):   Loading class de.defim.apk.bootmanager.Xposed
12-13 20:12:41.937 I/Xposed  (  577):     [BootManager] initialized
12-13 20:12:41.937 I/Xposed  (  577):   Loading class de.defim.apk.bootmanager.Xcheck
12-13 20:12:41.938 I/Xposed  (  577): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-2/base.apk
12-13 20:12:41.952 I/Xposed  (  577):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
12-13 20:12:41.954 I/Xposed  (  577): Loading modules from /data/app/com.devadvance.rootcloak2-1/base.apk
12-13 20:12:41.971 I/Xposed  (  577):   Loading class com.devadvance.rootcloak2.RootCloak
12-13 20:12:41.971 I/Xposed  (  577): Loading modules from /data/app/io.gavinhungry.xposed.oneplus.noquickpulldown-1/base.apk
12-13 20:12:41.984 I/Xposed  (  577):   Loading class io.gavinhungry.xposed.oneplus.noquickpulldown.NoQuickPulldown
12-13 20:12:41.984 I/Xposed  (  577): Loading modules from /data/app/com.ceco.sbdp-1/base.apk
12-13 20:12:42.000 I/Xposed  (  577):   Loading class com.ceco.sbdp.ModSbdp
12-13 20:12:42.001 I/Xposed  (  577): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
12-13 20:12:42.041 I/Xposed  (  577):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
12-13 20:12:42.057 I/Xposed  (  577): Loading modules from /data/app/com.glauber.android.xposed.volumesliderdelayfix-1/base.apk
12-13 20:12:42.077 I/Xposed  (  577):   Loading class com.glauber.android.xposed.volumesliderdelayfix.App
12-13 20:12:42.079 I/Xposed  (  577): Loading modules from /data/app/com.jodelXposed-1/base.apk
12-13 20:12:42.144 I/Xposed  (  577):   Loading class com.jodelXposed.App
12-13 20:12:42.173 I/Xposed  (  577): Loading modules from /data/app/com.jt5.xposed.chromepie-1/base.apk
12-13 20:12:42.202 I/Xposed  (  577):   Loading class com.jt5.xposed.chromepie.ChromePie
12-13 20:12:42.203 I/Xposed  (  577): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
12-13 20:12:42.227 I/Xposed  (  577):   Loading class ma.wanam.youtubeadaway.Xposed
12-13 20:12:42.228 I/Xposed  (  577): Loading modules from /data/app/tw.fatminmin.xposed.networkspeedindicator-1/base.apk
12-13 20:12:42.253 I/Xposed  (  577):   Loading class tw.fatminmin.xposed.networkspeedindicator.Module
12-13 20:12:42.257 I/Xposed  (  577): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
12-13 20:12:42.308 I/Xposed  (  577):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
12-13 20:12:42.325 I/Xposed  (  577): [Android N-ify] [INFO] XposedHook: Version 0.2.0 (5)
12-13 20:12:42.325 I/Xposed  (  577): [Android N-ify] [INFO] XposedHook: Official Build; Release: true (release)
12-13 20:12:42.328 I/Xposed  (  577): [Android N-ify] [WARNING] XposedHook: Can't read prefs file, default values will be applied in hooks!
12-13 20:12:42.328 I/Xposed  (  577): Loading modules from /data/app/com.gobbledygook.theawless.eventlock-1/base.apk
12-13 20:12:44.948 I/Xposed  (  577):   Loading class com.gobbledygook.theawless.eventlock.hooks.XposedUtilsHook
12-13 20:12:44.949 I/Xposed  (  577):   Loading class com.gobbledygook.theawless.eventlock.hooks.LockscreenHook
12-13 20:12:44.951 I/Xposed  (  577): Loading modules from /data/app/com.czbix.xposed.wifipassword-2/base.apk
12-13 20:12:44.964 I/Xposed  (  577):   Loading class com.czbix.xposed.wifipassword.Patch
12-13 20:12:46.278 I/Xposed  ( 1329): Amplify: Version 3.3.6c
12-13 20:12:46.278 I/Xposed  ( 1329): Amplify: Attempting 19to21 AlarmHook
12-13 20:12:46.279 I/Xposed  ( 1329): Amplify: Successful 19to21 AlarmHook
12-13 20:12:46.279 I/Xposed  ( 1329): Amplify: Attempting 21 WakeLockHook
12-13 20:12:46.282 I/Xposed  ( 1329): Amplify: Successful 21 WakeLockHook
12-13 20:12:46.283 I/Xposed  ( 1329): Amplify: Service Blocking Status: true
12-13 20:12:46.283 I/Xposed  ( 1329): Amplify: Attempting 23 ServiceHook
12-13 20:12:46.284 I/Xposed  ( 1329): Amplify: Successful 23 ServiceHook
12-13 20:13:03.147 I/Xposed  ( 4783): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:13:03.885 I/Xposed  ( 4783): EventLock: Added view to lockscreen
12-13 20:13:06.357 I/Xposed  ( 5772): [TwitchNoAds] Found Twitch App
12-13 20:13:14.736 I/Xposed  ( 6917): Hook M constructor success
12-13 20:13:15.392 I/Xposed  ( 5131): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:13:19.069 I/Xposed  ( 6130): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:13:24.031 I/Xposed  ( 5058): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:13:26.012 I/Xposed  ( 7769): Hook M constructor success
12-13 20:13:28.828 I/Xposed  ( 4783): EventLock: LooksUpdate
12-13 20:13:43.536 I/Xposed  ( 9389): YouTube: com.google.android.youtube 11.45.59 loaded!
12-13 20:13:43.537 I/Xposed  ( 9389): YouTube AdAway 3.4.1: Trying brute force way...
12-13 20:14:06.301 I/Xposed  ( 4783): EventLock: LooksUpdate
12-13 20:14:13.199 I/Xposed  (11610): [TwitchNoAds] Found Twitch App
12-13 20:14:14.087 I/Xposed  (11610): [TwitchNoAds] Found 1 possible container(s)
12-13 20:14:14.097 I/Xposed  (11610): [TwitchNoAds] Found and patched executor
12-13 20:14:14.100 I/Xposed  (11610): [TwitchNoAds] Found and patched executor
12-13 20:14:14.191 I/Xposed  (11610): [TwitchNoAds] Successfully suppressed ads
12-13 20:14:14.902 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:14:24.975 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:14:26.333 I/Xposed  (13932): [TwitchNoAds] Found Twitch App
12-13 20:14:27.606 I/Xposed  (13932): [TwitchNoAds] Found 1 possible container(s)
12-13 20:14:27.609 I/Xposed  (13932): [TwitchNoAds] Found and patched executor
12-13 20:14:27.611 I/Xposed  (13932): [TwitchNoAds] Found and patched executor
12-13 20:14:27.611 I/Xposed  (13932): [TwitchNoAds] Successfully suppressed ads
12-13 20:14:34.978 I/Xposed  (14455): [TwitchNoAds] Found Twitch App
12-13 20:14:35.537 I/Xposed  (14455): [TwitchNoAds] Found 1 possible container(s)
12-13 20:14:35.541 I/Xposed  (14455): [TwitchNoAds] Found and patched executor
12-13 20:14:35.546 I/Xposed  (14455): [TwitchNoAds] Found and patched executor
12-13 20:14:35.559 I/Xposed  (14455): [TwitchNoAds] Successfully suppressed ads
12-13 20:14:43.057 I/Xposed  (15021): YouTube: com.google.android.youtube 11.45.59 loaded!
12-13 20:14:43.057 I/Xposed  (15021): YouTube AdAway 3.4.1: Trying brute force way...
12-13 20:16:23.716 I/Xposed  ( 7769): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:16:54.740 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpCollectorWakeLock.  Max Interval: 240000 Time since last granted: 271767
12-13 20:16:54.752 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpWakeLock.  Max Interval: 240000 Time since last granted: 271779
12-13 20:17:11.425 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:17:16.367 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:17:53.590 I/Xposed  (18563): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:17:58.244 I/Xposed  (18001): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:20:55.828 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpCollectorWakeLock.  Max Interval: 240000 Time since last granted: 241088
12-13 20:20:55.847 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpWakeLock.  Max Interval: 240000 Time since last granted: 241095
12-13 20:21:19.675 I/Xposed  ( 1329): [Android N-ify] [ERROR] StatusBarHeaderHooks: Couldn't change qs_dual_tile_height (NotFoundException)
12-13 20:21:51.821 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:25:00.251 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpCollectorWakeLock.  Max Interval: 240000 Time since last granted: 244423
12-13 20:25:00.258 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpWakeLock.  Max Interval: 240000 Time since last granted: 244411
12-13 20:28:47.143 I/Xposed  ( 4783): EventLock: LooksUpdate
12-13 20:28:48.326 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:29:32.424 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpCollectorWakeLock.  Max Interval: 240000 Time since last granted: 272173
12-13 20:29:32.450 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpWakeLock.  Max Interval: 240000 Time since last granted: 272192
12-13 20:33:51.610 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpWakeLock.  Max Interval: 240000 Time since last granted: 259160
12-13 20:37:09.080 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:37:15.983 I/Xposed  ( 4783): EventLock: LooksUpdate
12-13 20:37:19.302 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:37:34.572 I/Xposed  ( 4783): EventLock: LooksUpdate
12-13 20:37:37.007 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF
12-13 20:39:07.569 I/Xposed  ( 1329): Amplify: Allowing Wakelock NlpWakeLock.  Max Interval: 240000 Time since last granted: 315959
12-13 20:40:05.537 I/Xposed  ( 4783): EventLock: android.intent.action.SCREEN_OFF

**Comment by theawless** [comment]
I can see that new events are not loaded in your case, are you sure you are giving permissions to the application? Make sure you give it permanently. Some permission managers give permissions only temporarily.

**Comment by Latschenharry** [comment]
![screenshot_20161214-103459](https://cloud.githubusercontent.com/assets/12736979/21177145/130cf4a2-c1ea-11e6-8d2f-a46b044996e5.png)

**Comment by theawless** [comment]
Can you get the log?
[log cat how to](http://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat)

**Comment by Latschenharry** [comment]
[logcat.txt](https://github.com/theawless/EventLock/files/652128/logcat.txt)

here is the logcat file as txt, because pastebin has an upload limit.-

**Comment by theawless** [comment]
Thanks for the logcat. I fixed the error (hopefully) in 51e3526cfae92995b843c257f7642883e9974d5c
Check the new version I put in xposed.

**Comment by Latschenharry** [comment]
Thank you very much for your support. It is working now.
Love your app

**Comment by theawless** [comment]
Glad I could help.
