### ISSUE TITLE
Time is not visable when two row Event name

### ISSUE THREAD

**Issue by androiduser5** [theawless/EventLock#9]
Dear devs of EventLock,

when viewing an event that is displayed with two rows, because of a long name, the time is invisable for those events.
It appears when swapping the keyboard for unlock up and down again.
It would be nice if you could fix that

Greetings
Sebastian

**Comment by theawless** [comment]
Can you me give a screenshot?

**Comment by androiduser5** [comment]
Sure. Here is one:
http://s24.postimg.org/rtpaaqnqt/tmp_16010_Screenshot_2016_12_15_15_09_2515157598.png

**Comment by androiduser5** [comment]
@I forgot to mention that this will only appear when the initial event is an one row title event. After scrolling only the two rows will be shown. 
If the initial event is a two road event, all events will be shown correct. 
Initial event means, that this event is the next event in the calender timeline and the first shown when waking up the phone.

**Comment by theawless** [comment]
d34946c
